oauth2:
  user:
    #      naver:
    #        client-id:
    #        client-secret:
    #        redirect-uri:
    kakao:
      client-id: cb7a84398dab0d6fb9ecdc4e302810f0
      client-secret: 9xR1fuGYcKjRE6gjlSuDANnWj8qGskGd
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  provider:
    #      naver:
    #        token-uri: https://nid.naver.com/oauth2.0/token
    #        user-info-uri: https://openapi.naver.com/v1/nid/me
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  token:
    secret-key: secret_key
