spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anitime?serverTimezone=Asia/Seoul
    username: root
    password: root1234
  profiles:
    include: oauth

  # springfox-swagger(?? 3.0.0)? spring-boot(2.6.2) ???? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # jpa ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

    thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      cache: false
      encoding: UTF-8

